
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.annotator.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler
  namespace: {{ .Values.scheduler.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: annotator
  namespace: {{ .Values.annotator.namespace }}