apiVersion: v1
kind: Namespace
metadata:
  name: crane-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: annotator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - namespaces
  verbs:
  - list
  - watch
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - patch

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: annotator
  namespace: crane-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: annotator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: annotator
subjects:
- kind: ServiceAccount
  name: annotator
  namespace: crane-system