apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: /users/zarhu/.kube/config_cloud
profiles:
  - schedulerName: crane-scheduler
    plugins:
      filter:
        enabled:
          - name: Dummy
      postFilter:
        enabled:
          - name: Dummy